### ISSUE TITLE
extract_vars() might fail during is_moving_domain() call

### ISSUE THREAD

**Issue by bbonenfant** [NCAR/wrf-python#81] opened 2019-01-08 22:37 UTC
When attempting to extract variables from a WRF output file that has previously been dumped to a file using xarray, I receive the following error:
```
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File ".../weatherclasses/netcdf.py", line 108, in unpack
    self._cache = extract_vars(self._netcdf_objects, ALL_TIMES, self._extraction_variables)
  File ".../venv/lib/python3.7/site-packages/wrf/util.py", line 2280, in extract_vars
    for var in varlist}
  File ".../venv/lib/python3.7/site-packages/wrf/util.py", line 2280, in <dictcomp>
    for var in varlist}
  File ".../venv/lib/python3.7/site-packages/wrf/util.py", line 2216, in _extract_var
    method, squeeze, meta, _key)
  File ".../venv/lib/python3.7/site-packages/wrf/util.py", line 2118, in combine_files
    squeeze, meta, _key)
  File ".../venv/lib/python3.7/site-packages/wrf/util.py", line 1596, in _cat_files
    is_moving = is_moving_domain(wrfseq, varname, _key=_key)
  File ".../venv/lib/python3.7/site-packages/wrf/util.py", line 785, in is_moving_domain
    lon0 = lons[zero_idxs]
IndexError: too many indices for array
```
Within the `util.py` file this corresponds to the following lines:
```
if varname is not None:
        try:
            coord_str = getattr(first_wrfnc.variables[varname], "coordinates")
            # scipy.io.netcdf stores attributes as bytes rather than str
            if isinstance(coord_str, str):
                coord_names = coord_str.split()
            else:
                coord_names = coord_str.decode().split()
        except AttributeError:
            # Variable doesn't have a coordinates attribute, use the 
            # arguments
            lon_coord = lonvar
            lat_coord = latvar
        else:   
            lon_coord = coord_names[0]
            lat_coord = coord_names[1]
    else:
        lon_coord = lonvar
        lat_coord = latvar
...
    lats = first_wrfnc.variables[lat_coord][:]
    lons = first_wrfnc.variables[lon_coord][:]
    
    zero_idxs = [0]*len(lats.shape)  # PyNIO doesn't have ndim
    last_idxs = list(zero_idxs)
    last_idxs[-2:] = [-1]*2
    
    zero_idxs = tuple(zero_idxs)
    last_idxs = tuple(last_idxs)
    
    lat0 = lats[zero_idxs]
    lat1 = lats[last_idxs]
*   lon0 = lons[zero_idxs]
    lon1 = lons[last_idxs]
```
where the starred line is where the error occurs. 
Upon inspection of the NetCDF4 class instance I was providing, I noticed that the `coordinates` attributes does not have its order preserved when written to file. For example:
```
>>> wnc._netcdf_objects[0].variables['V']
<class 'netCDF4._netCDF4.Variable'>
float32 V(Time, z, y_stag, x)
    _FillValue: nan
    FieldType: 104
    MemoryOrder: XYZ
    description: y-wind component
    units: m s-1
    stagger: Y
    coordinates: XLONG_V XTIME XLAT_V
unlimited dimensions: 
current shape = (1, 32, 12, 11)
filling on
```
I've found that disabling metadata during extraction is a work-around for this, but is not ideal. I believe that instead of making the assumption that the longitude and latitude coordinates will be the first and second coordinates that more care must be taken to ensure the correct coordinates are chosen.

Thank you.

**Comment by bladwig1** [comment] 2019-01-08 23:03
Why is the order changing for your 'coordinates' attribute in the file you've written? That's just a string in a standard WRF-ARW output file, ordered in "Fortran ordering" to align with the dimensions. The order of these variable names does matter for a WRF file.

**Comment by bbonenfant** [comment] 2019-01-09 04:00
I'm not sure, but is appears that xarray must reconstruct the string when writing to a file. Here's a simple script to illustrate what I am doing and what I am receiving as output:
```
from os import path
from tempfile import TemporaryDirectory
import xarray as xr

wnc = xr.open_dataset('test_data/wrfout_d01_2018-12-06_00:00:00')
with TemporaryDirectory() as tempdir:
    tempfile = path.join(tempdir, 'tempfile.nc')
    wnc.to_netcdf(tempfile)
    wnc2 = xr.open_dataset(tempfile)

print(f'Original: {wnc._file_obj.ds.variables["V"].coordinates}')
print(f'     New: {wnc2._file_obj.ds.variables["V"].coordinates}')
```
Output:
```
Original: XLONG_V XLAT_V XTIME
     New: XLONG_V XTIME XLAT_V
```
For reference I'm trying to do some processing of the netcdf files with xarray but still use this package to get diagnostic variables.

**Comment by bladwig1** [comment] 2019-01-10 19:15
I was unable to reproduce the coordinate names being reordered with xarray, but checked in a fix anyhow. You can click the commit link in the comment above to see what you would need to hack up in your own code to work around the problem. It might be a while before another release is out.

**Comment by bladwig1** [comment] 2019-01-16 23:37
For files written from WRF itself, the order is fixed, but for xarray, it *thinks* it's a NetCDF-CF file. NetCDF-CF has different conventions regarding the coordinates attribute. I suspect when xarray writes the file, it just dumps the keys from the coords dictionary (which I suspect is unordered), so that would explain the random behavior. WRF files aren't NetCDF-CF files, although they added some CF things to it. In any case, I'm glad the fix worked. I'll go ahead and close the issue.

**Closed** 2019-01-16 23:46 UTC
