### ISSUE TITLE
Downloading WRF. netcdf files for tutorials

### ISSUE THREAD

**Issue by farooqspecials** [NCAR/wrf-python#84] opened 2019-02-03 20:49 UTC
Where can i download WRF  NETCDF FILES for tutorials   wrfout_d01_2016-10-07_00_00_00.nc

**Comment by bladwig1** [comment] 2019-02-05 04:40
The file is gigantic, so it's not publicly available. Do you have an account on the Cheyenne supercomputer? 

In any case, I'm out of the office until next week, but I can try to upload it somewhere when I get back.

**Comment by smartlixx** [comment] 2020-04-02 12:32
@bladwig1 Is there any update to this thread? I am also interested in reproducing the plots in the document.

**Comment by sxcgc** [comment] 2020-09-03 03:28
we need it.

**Comment by michaelavs** [comment] 2021-01-19 22:20
Hi everyone,
We are working on a way to maybe make the file in question downloadable for users. Currently, the raw file is over 13 GB, but has been subsetted to only have the data/variables needed to run the "plotting examples" from the wrf-python website. That being said, the file is still about 3.5 GB so it will most likely take a decent amount of time to download, but you should be able to download it from this link: https://drive.google.com/file/d/1QB9Fj5xvXwLC-_bp6ydCP7ESUOZ0rpsy/view?usp=sharing . 

Please let me know if there are any issues you encounter when opening or downloading the file from Google Drive.

**Comment by clyne** [comment] 2021-01-19 23:23
@michaelavs as part of Project Pythia we promised to host large (to big for GitHub) example data on NCAR's data repository:

https://www2.cisl.ucar.edu/dash

which is intended for exactly this purpose. We've not put any data out there yet, but this looks like the perfect opportunity :-). We've already been granted an allocation, but just need to figure out how to deposit and manage the data.  I'll send you a separate email with the details.

cc: @erogluorhan

**Comment by erogluorhan** [comment] 2021-01-20 01:29
> @michaelavs as part of Project Pythia we promised to host large (to big for GitHub) example data on NCAR's data repository:
> 
> https://www2.cisl.ucar.edu/dash
> 
> which is intended for exactly this purpose. We've not put any data out there yet, but this looks like the perfect opportunity :-). We've already been granted an allocation, but just need to figure out how to deposit and manage the data. I'll send you a separate email with the details.
> 
> cc: @erogluorhan

This sounds a great opportunity for all; i.e. Project Pythia, the GeoCAT team's needs to publish large datasets for users withput Cheyenne access, and the community users of those large datasets. 

@michaelavs please let me know if you need anything with DASH. (And thank you for having already provided a quick Google drive solution for folks)

**Comment by michaelavs** [comment] 2021-02-16 15:43
Hi @farooqspecials and @sxcgc,
The link to the file (now hosted on DASH) has been embedded on the wrf-python website on the [plotting examples page](https://wrf-python.readthedocs.io/en/latest/plot.html). If there are any issues with accessing or downloading the file from this source, please let us know. Otherwise, I will be marking this issue as resolved in the coming days.

**Comment by LekhyaJE** [comment] 2023-05-25 08:56
the DASH link which you have provided seems to redirect to the ncarucar page and its asking for a username and password. How else do we access the wrf output data

**Comment by kafitzgerald** [comment] 2023-05-25 15:14
> the DASH link which you have provided seems to redirect to the ncarucar page and its asking for a username and password. How else do we access the wrf output data

Which link are you referring to?  

The Google Drive links are likely broken at this point, but the [link to the data on GDEX (a rebranding of DASH](https://gdex.ucar.edu/dataset/78_clyne_wrf.html) in the [plotting examples page](https://wrf-python.readthedocs.io/en/latest/plot.html) referenced above seems to work for me without authentication and should persist going forward.

Let us know if you're having trouble with that.

**Closed** 2023-05-30 21:18 UTC
Labels: question, support
